parameters:
    lz_aztec_notification.bundle.ns: LZAztec\NotificationBundle
    lz_aztec_notification.service.ns: %lz_aztec_notification.bundle.ns%\Service
    lz_aztec_notification.adapter.ns: %lz_aztec_notification.bundle.ns%\Adapter

services:

  # Adapters
  lz_aztec_notification.adapter.realplexor:
    class: %lz_aztec_notification.adapter.ns%\Comet\RealplexorAdapter
    arguments: [%lz_aztec_notification.realplexor_host%, %lz_aztec_notification.realplexor_port%, %lz_aztec_notification.realplexor_ns%]

  # Notification service
  lz_aztec_notification.service.notification:
    class: %lz_aztec_notification.service.ns%\Notification\NotificationService

  # Twig extension
  lz_aztec_notification.twig.extension:
    class: %lz_aztec_notification.service.ns%\Twig\Extension\NotificationExtension
    arguments: [ @service_container ]
    tags:
        - { name: twig.extension }